[package]
name = "near-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
near-sdk = { version = "5.8.1", features = ["legacy"] }
borsh = "1.3.1"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
